import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

function source(path: string): string {
  return readFileSync(resolve(process.cwd(), path), 'utf8')
}

describe('superfície de atendimento compartilhado', () => {
  it('segue o arquétipo master-detail com painel de contexto colapsável', () => {
    const page = source('app/components/communication/CommunicationWorkspacePage.vue')
    const timeline = source('app/components/communication/TimelinePanel.vue')
    expect(page).toContain('communication-list-panel')
    expect(page).toContain('CommunicationTimelinePanel')
    expect(page).toContain('CommunicationContextPanel')
    expect(page).toContain('contextOpen')
    expect(page).toContain('toggleContext')
    expect(page).toContain('selectedConversation.value && contextOpen')
    expect(page).toContain('smaller(\'lg\')')
    expect(page).toContain('communication-mobile-timeline')
    expect(page).toContain('communication-mobile-context')
    expect(page.match(/<USlideover/g)?.length).toBeGreaterThanOrEqual(2)
    expect(page).toContain('UDashboardSidebarCollapse')
    expect(page).not.toContain('overflow-x-auto')
    expect(page).not.toMatch(/CommunicationContextPanel[\s\S]*class="hidden xl:flex"/)
    expect(timeline).toContain('i-lucide-user')
    expect(timeline).toContain('communication-context-toggle')
    expect(timeline).toContain('toggleContext')
    expect(timeline).not.toContain('xl:hidden')
  })

  it('composer cobre leitura, nota interna, canned response, citação e mídia privada', () => {
    const composer = source('app/components/communication/Composer.vue')
    const timeline = source('app/components/communication/TimelinePanel.vue')
    expect(composer).toContain('Seu perfil possui acesso somente para leitura')
    expect(composer).toContain('Nota interna')
    expect(composer).toContain('Resposta pronta')
    expect(composer).toContain('replyToMessageId')
    expect(composer).toContain('type="file"')
    expect(timeline).toContain('<CommunicationComposer')
    expect(timeline).toContain('Citar mensagem')
    expect(timeline).toContain('message.source === \'FISCAL_AUTOMATION\'')
    expect(timeline).toContain('media === \'AUDIO\'')
    expect(timeline).toContain('download')
    expect(timeline).toContain('loading && !conversation.messages?.length')
    expect(composer).toContain('emit(\'presence\', \'COMPOSING\')')
    expect(composer).toContain('emit(\'presence\', \'PAUSED\')')
    expect(composer).toContain('emit(\'presence\', \'RECORDING\')')
    expect(composer).toContain('MediaRecorder')
    expect(composer).toContain('shouldSubmitCommunicationComposer')
    expect(composer).toContain('kind: file.value ? fileKind.value : \'TEXT\'')
    expect(composer).toContain('ptt: Boolean(file.value && ptt.value)')
    expect(composer).toContain('accept="image/webp,.webp"')
  })

  it('hydrate silencioso evita skeleton com timeline em cache', () => {
    const workspace = source('app/composables/useCommunicationWorkspace.ts')
    const timeline = source('app/components/communication/TimelinePanel.vue')
    expect(workspace).toContain('async function refreshConversationDetail')
    expect(workspace).toContain('options: { silent?: boolean }')
    expect(workspace).toContain('await refreshConversationDetail(selectedId, { silent: true })')
    expect(workspace).toContain('refreshConversationDetail(conversation.id, { silent: true })')
    expect(timeline).toContain('loading && !conversation.messages?.length')
    expect(timeline).not.toMatch(/v-if="loading"\s+class="space-y-4"/)
  })

  it('representa tipos 1x1 e expõe somente ações tipadas do backend', () => {
    const content = source('app/components/communication/MessageContent.vue')
    const timeline = source('app/components/communication/TimelinePanel.vue')
    const api = source('app/composables/api/createCommunicationApi.ts')
    const workspace = source('app/composables/useCommunicationWorkspace.ts')
    for (const kind of ['LOCATION', 'CONTACT', 'POLL', 'INTERACTIVE', 'STICKER']) {
      expect(content).toContain(`message.kind === '${kind}'`)
    }
    expect(content).toContain('message.metadata?.revoked')
    expect(content).toContain('attachment.preview_url')
    expect(content).toContain('<audio')
    expect(content).toContain('<video')
    expect(content).toContain('markAudioPlayed')
    expect(timeline).toContain('message.metadata?.reactions')
    expect(timeline).toContain('COMMUNICATION_REACTION_EMOJIS')
    expect(timeline).toContain('scrollToMessage')
    expect(timeline).toContain('Editar mensagem')
    expect(timeline).toContain('Apagar para todos')
    expect(api).toContain('/messages/${messageId}/edit')
    expect(api).toContain('/messages/${messageId}/reaction')
    expect(api).toContain('/messages/${messageId}/poll-votes')
    expect(workspace).toContain('isCommunicationEphemeralEvent')
    expect(workspace).toContain('signalTimers')
    expect(workspace).toContain('const durable = incoming.filter')
  })

  it('prioriza a identidade fiscal e mantém contato e telefone como contexto', () => {
    const list = source('app/components/communication/ConversationList.vue')
    const timeline = source('app/components/communication/TimelinePanel.vue')
    expect(list).toContain('communicationDisplayName(conversation)')
    expect(list).toContain('communicationContactLabel(conversation)')
    expect(timeline).toContain(':title="communicationDisplayName(conversation)"')
    expect(timeline).toContain('communicationContactLabel(conversation)')
  })

  it('contexto cobre fila, responsável, snooze, labels, clientes e expurgo', () => {
    const context = source('app/components/communication/ContextPanel.vue')
    expect(context).toContain('Responsável')
    expect(context).toContain('Fila / departamento')
    expect(context).toContain('Adiar conversa')
    expect(context).toContain('Marcadores')
    expect(context).toContain('Clientes vinculados')
    expect(context).toContain('Exportar contato')
    expect(context).toContain('Expurgar dados')
    expect(context).toContain('Mensagens temporárias')
    expect(context).toContain('signals?.contact?.available')
    expect(context).toContain('communication-context-close')
    expect(context).toContain('resizable')
  })

  it('administra switches, inbox, QR, membros, políticas e destinatários sem egress externo', () => {
    const admin = source('app/components/communication/AdministrationSlideover.vue')
    const inbox = source('app/components/communication/InboxAdminCard.vue')
    const policy = source('app/components/communication/AutomationPolicyCard.vue')
    const recipients = source('app/components/communication/RecipientConfigurationPanel.vue')
    expect(admin).toContain('defaults permanecem fail-closed')
    expect(admin).toContain('CommunicationInboxAdminCard')
    expect(admin).toContain('CommunicationAutomationPolicyCard')
    expect(admin).toContain('CommunicationRecipientConfigurationPanel')
    expect(inbox).toContain('QRCode.toDataURL')
    expect(inbox).toContain('Membros autorizados')
    expect(policy).toContain('SKIPPED_NO_DOCUMENT')
    expect(policy).toContain('Inbox geral')
    expect(recipients).toContain('SELECTED')
    expect(inbox).not.toMatch(/https?:\/\//)
  })

  it('integra REST office-scoped e navegação permission-aware', () => {
    const api = source('app/composables/api/createCommunicationApi.ts')
    const navigation = source('app/utils/navigation.ts')
    const routes = source('app/utils/communication-routes.ts')
    expect(api).toContain('const base = \'/api/v1/communication\'')
    expect(api).toContain('/automation-recipients')
    expect(api).toContain('/events')
    expect(api).toContain('FormData')
    expect(navigation).toContain('id: \'communication\'')
    expect(navigation).toContain('to: \'/communication\'')
    expect(navigation).toContain('path.startsWith(\'/communication/\')')
    expect(navigation).toContain('canViewCommunication(user)')
    expect(routes).toContain('conversations/${id}')
    expect(routes).toContain('communicationConversationPath')
    expect(source('app/pages/communication/index.vue')).toContain('CommunicationWorkspacePage')
    expect(source('app/pages/communication/conversations/[id].vue')).toContain('CommunicationWorkspacePage')
  })
})
